all: compile test checkstyle

compile:
	@echo "nothing to compile"

test:
	@echo "nothing to test"

checkstyle:
	@echo "nothing to check"

clean:
	@echo "nothing to clean"

sql:
	cat movies.sql queries.sql | sqlite3
